In [46]:
import pandas as pd
import numpy as np

In [47]:
bats = pd.read_csv("batsman_runs_ipl - batsman_runs_ipl.csv")
bats

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [48]:

bats.shape

(605, 2)

In [49]:
diabetes = pd.read_csv("diabetes - diabetes.csv")
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [50]:
diabetes.shape

(768, 9)

In [51]:
ipl = pd.read_csv("ipl-matches - ipl-matches.csv")
print(ipl)

          ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2
2    1312198     Kolkata  2022-05-25     2022   Eliminator
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1
4    1304116      Mumbai  2022-05-22     2022           70
..       ...         ...         ...      ...          ...
945   335986     Kolkata  2008-04-20  2007/08            4
946   335985      Mumbai  2008-04-20  2007/08            5
947   335984       Delhi  2008-04-19  2007/08            3
948   335983  Chandigarh  2008-04-19  2007/08            2
949   335982   Bangalore  2008-04-18  2007/08            1

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans
1    Royal Challengers Bangalore             Rajasthan Royals
2    Royal Challengers Bangalore         Lucknow Super Giants
3               Rajasthan Royals               Gujarat Titans
4            Sunrisers Hyderabad                 Punjab Kings
..                           ...                          ...
945        Kolkata Knight Riders              Deccan Chargers
946               Mumbai Indians  Royal Challengers Bangalore
947             Delhi Daredevils             Rajasthan Royals
948              Kings XI Punjab          Chennai Super Kings
949  Royal Challengers Bangalore        Kolkata Knight Riders

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals
2                         Eden Gardens, Kolkata         Lucknow Super Giants
3                         Eden Gardens, Kolkata               Gujarat Titans
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad
..                                          ...                          ...
945                                Eden Gardens              Deccan Chargers
946                            Wankhede Stadium               Mumbai Indians
947                            Feroz Shah Kotla             Rajasthan Royals
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0
1          field         N             Rajasthan Royals  Wickets     7.0
2          field         N  Royal Challengers Bangalore     Runs    14.0
3          field         N               Gujarat Titans  Wickets     7.0
4            bat         N                 Punjab Kings  Wickets     5.0
..           ...       ...                          ...      ...     ...
945          bat         N        Kolkata Knight Riders  Wickets     5.0
946          bat         N  Royal Challengers Bangalore  Wickets     5.0
947          bat         N             Delhi Daredevils  Wickets     9.0
948          bat         N          Chennai Super Kings     Runs    33.0
949        field         N        Kolkata Knight Riders     Runs   140.0

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...
..     ...             ...                                                ...
945    NaN       DJ Hussey  ['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...
946    NaN      MV Boucher  ['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...
947    NaN     MF Maharoof  ['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...
948    NaN      MEK Hussey  ['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...
949    NaN     BB McCullum  ['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...

                                          Team2Players        Umpire1  \
0    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...    CB Gaffaney
1    ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...    CB Gaffaney
2    ['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...  J Madanagopal
3    ['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...   BNJ Oxenford
4    ['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...   AK Chaudhary
..                                                 ...            ...
945  ['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...      BF Bowden
946  ['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...       SJ Davis
947  ['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...      Aleem Dar
948  ['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...      MR Benson
949  ['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...      Asad Rauf

            Umpire2
0       Nitin Menon
1       Nitin Menon
2          MA Gough
3         VK Sharma
4     NA Patwardhan
..              ...
945     K Hariharan
946       DJ Harper
947  GA Pratapkumar
948      SL Shastri
949     RE Koertzen

[950 rows x 20 columns]

In [52]:
ipl.shape

(950, 20)

In [53]:
movies = pd.read_csv("movies - movies.csv")
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [54]:
movies.shape

(1629, 18)

In [55]:
ipl.head(10)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,N,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
9,1304111,Mumbai,2022-05-17,2022,65,Sunrisers Hyderabad,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,N,Sunrisers Hyderabad,Runs,3.0,NaN,RA Tripathi,"['Abhishek Sharma', 'PK Garg', 'RA Tripathi', ...","['RG Sharma', 'Ishan Kishan', 'DR Sams', 'Tila...",CB Gaffaney,N Pandit

In [56]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

In [57]:
b = ipl.groupby('MatchNumber').head(1)
b

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,981015,Delhi,2016-05-25,2016,Elimination Final,Sunrisers Hyderabad,Kolkata Knight Riders,Feroz Shah Kotla,Kolkata Knight Riders,field,N,Sunrisers Hyderabad,Runs,22.0,NaN,MC Henriques,"['DA Warner', 'S Dhawan', 'MC Henriques', 'Yuv...","['RV Uthappa', 'G Gambhir', 'C Munro', 'MK Pan...",M Erasmus,C Shamshuddin
556,598069,Hyderabad,2013-05-19,2013,72,Sunrisers Hyderabad,Kolkata Knight Riders,"Rajiv Gandhi International Stadium, Uppal",Kolkata Knight Riders,bat,N,Sunrisers Hyderabad,Wickets,5.0,NaN,PA Patel,"['PA Patel', 'S Dhawan', 'GH Vihari', 'CL Whit...","['MS Bisla', 'G Gambhir', 'JH Kallis', 'EJG Mo...",Asad Rauf,S Asnani
557,598067,Pune,2013-05-19,2013,71,Pune Warriors,Delhi Daredevils,Subrata Roy Sahara Stadium,Pune Warriors,bat,N,Pune Warriors,Runs,38.0,NaN,LJ Wright,"['RV Uthappa', 'AJ Finch', 'MK Pandey', 'Yuvra...","['DPMD Jayawardene', 'DA Warner', 'B Chipli', ...",NJ Llong,SJA Taufel
776,419164,Mumbai,2010-04-24,2009/10,3rd Place Play-Off,Royal Challengers Bangalore,Deccan Chargers,Dr DY Patil Sports Academy,Deccan Chargers,bat,N,Royal Challengers Bangalore,Wickets,9.0,NaN,A Kumble,"['JH Kallis', 'R Dravid', 'KP Pietersen', 'RV ...","['AC Gilchrist', 'MD Mishra', 'Anirudh Singh',...",RE Koertzen,SJA Taufel
777,419163,Mumbai,2010-04-22,2009/10,Semi Final,Chennai Super Kings,Deccan Chargers,Dr DY Patil Sports Academy,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,38.0,NaN,DE Bollinger,"['M Vijay', 'ML Hayden', 'SK Raina', 'S Badrin...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'RG S...",BR Doctrove,RB Tiffin

In [58]:
c = ipl.groupby('City').head(1)
c

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,N,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
13,1304107,Pune,2022-05-14,2022,61,Kolkata Knight Riders,Sunrisers Hyderabad,"Maharashtra Cricket Association Stadium, Pune",Kolkata Knight Riders,bat,N,Kolkata Knight Riders,Runs,54.0,NaN,AD Russell,"['VR Iyer', 'AM Rahane', 'N Rana', 'SS Iyer', ...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",AK Chaudhary,KN Ananthapadmanabhan
74,1254117,Dubai,2021-10-15,2021,Final,Chennai Super Kings,Kolkata Knight Riders,Dubai International Cricket Stadium,Kolkata Knight Riders,field,N,Chennai Super Kings,Runs,27.0,NaN,F du Plessis,"['RD Gaikwad', 'F du Plessis', 'RV Uthappa', '...","['Shubman Gill', 'VR Iyer', 'N Rana', 'SP Nari...",Nitin Menon,RK Illingworth
75,1254116,Sharjah,2021-10-13,2021,Qualifier 2,Delhi Capitals,Kolkata Knight Riders,Sharjah Cricket Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,3.0,NaN,VR Iyer,"['PP Shaw', 'S Dhawan', 'MP Stoinis', 'SS Iyer...","['Shubman Gill', 'VR Iyer', 'N Rana', 'RA Trip...",KN Ananthapadmanabhan,MA Gough
79,1254088,Abu Dhabi,2021-10-08,2021,55,Mumbai Indians,Sunrisers Hyderabad,"Zayed Cricket Stadium, Abu Dhabi",Mumbai Indians,bat,N,Mumbai Indians,Runs,42.0,NaN,Ishan Kishan,"['RG Sharma', 'Ishan Kishan', 'HH Pandya', 'KA...","['JJ Roy', 'Abhishek Sharma', 'MK Pandey', 'Mo...",Tapan Sharma,VK Sharma
106,1254085,Delhi,2021-05-02,2021,28,Rajasthan Royals,Sunrisers Hyderabad,"Arun Jaitley Stadium, Delhi",Sunrisers Hyderabad,field,N,Rajasthan Royals,Runs,55.0,NaN,JC Buttler,"['JC Buttler', 'YBK Jaiswal', 'SV Samson', 'R ...","['MK Pandey', 'JM Bairstow', 'KS Williamson', ...",C Shamshuddin,CB Gaffaney
114,1254077,Chennai,2021-04-25,2021,20,Delhi Capitals,Sunrisers Hyderabad,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,bat,Y,Delhi Capitals,SuperOver,NaN,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SPD Smith'...","['DA Warner', 'JM Bairstow', 'KS Williamson', ...",CB Gaffaney,KN Ananthapadmanabhan
194,1181768,Hyderabad,2019-05-12,2019,Final,Mumbai Indians,Chennai Super Kings,Rajiv Gandhi International Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,1.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",IJ Gould,Nitin Menon
195,1181767,Visakhapatnam,2019-05-10,2019,Qualifier,Delhi Capitals,Chennai Super Kings,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,F du Plessis,"['PP Shaw', 'S Dhawan', 'C Munro', 'SS Iyer', ...","['F du Plessis', 'SR Watson', 'SK Raina', 'AT ...",BNJ Oxenford,S Ravi
198,1178430,Chandigarh,2019-05-05,2019,55,Chennai Super Kings,Kings XI Punjab,Punjab Cricket Association IS Bindra Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,6.0,NaN,KL Rahul,"['F du Plessis', 'SR Watson', 'SK Raina', 'MS ...","['KL Rahul', 'CH Gayle', 'N Pooran', 'MA Agarw...",C Shamshuddin,KN Ananthapadmanabhan
200,1178429,Bengaluru,2019-05-04,2019,54,Sunrisers Hyderabad,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,4.0,NaN,SO Hetmyer,"['WP Saha', 'MJ Guptill', 'MK Pandey', 'KS Wil...","['PA Patel', 'V Kohli', 'AB de Villiers', 'SO ...",AK Chaudhary,NJ Llong
209,1178420,Jaipur,2019-04-27,2019,45,Sunrisers Hyderabad,Rajasthan Royals,Sawai Mansingh Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JD Unadkat,"['DA Warner', 'KS Williamson', 'MK Pandey', 'V...","['AM Rahane', 'LS Livingstone', 'SV Samson', '...",A Nand Kishore,YC Barde
266,1136608,Indore,2018-05-14,2018,48,Kings XI Punjab,Royal Challengers Bangalore,Holkar Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,10.0,NaN,UT Yadav,"['KL Rahul', 'CH Gayle', 'KK Nair', 'AJ Finch'...","['V Kohli', 'PA Patel', 'MM Ali', 'AB de Villi...",BNJ Oxenford,VK Sharma
315,1082649,Bangalore,2017-05-19,2017,Qualifier 2,Mumbai Indians,Kolkata Knight Riders,M Chinnaswamy Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,6.0,NaN,KV Sharma,"['LMP Simmons', 'PA Patel', 'AT Rayudu', 'RG S...","['CA Lynn', 'SP Narine', 'G Gambhir', 'RV Utha...",NJ Llong,Nitin Menon
321,1082643,Kanpur,2017-05-13,2017,53,Gujarat Lions,Sunrisers Hyderabad,Green Park,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,8.0,NaN,Mohammed Siraj,"['DR Smith', 'Ishan Kishan', 'SK Raina', 'KD K...","['DA Warner', 'S Dhawan', 'MC Henriques', 'V S...",AK Chaudhary,Nitin Menon
339,1082625,Rajkot,2017-04-29,2017,35,Gujarat Lions,Mumbai Indians,Saurashtra Cricket Association Stadium,Gujarat Lions,bat,Y,Mumbai Indians,SuperOver,NaN,NaN,KH Pandya,"['Ishan Kishan', 'BB McCullum', 'SK Raina', 'A...","['PA Patel', 'JC Buttler', 'N Rana', 'RG Sharm...",AK Chaudhary,CB Gaffaney
377,981011,Raipur,2016-05-22,2016,56,Delhi Daredevils,Royal Challengers Bangalore,Shaheed Veer Narayan Singh International Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,6.0,NaN,V Kohli,"['Q de Kock', 'RR Pant', 'KK Nair', 'SV Samson...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'KL ...",A Nand Kishore,BNJ Oxenford
434,829821,Ranchi,2015-05-22,2015,Qualifier 2,Chennai Super Kings,Royal Challengers Bangalore,JSCA International Stadium Complex,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,3.0,NaN,A Nehra,"['DR Smith', 'MEK Hussey', 'F du Plessis', 'SK...","['CH Gayle', 'V Kohli', 'AB de Villiers', 'Man...",AK Chaudhary,CB Gaffaney
512,734009,Cuttack,2014-05-14,2014,40,Kolkata Knight Riders,Mumbai Indians,Barabati Stadium,Kolkata Knight Riders,field,N,Kolkata Knight Riders,Wickets,6.0,NaN,RV Uthappa,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'YK P...","['LMP Simmons', 'CM Gautam', 'AT Rayudu', 'RG ...",AK Chaudhary,NJ Llong
559,598066,Dharamsala,2013-05-18,2013,69,Kings XI Punjab,Mumbai Indians,Himachal Pradesh Cricket Association Stadium,Mumbai Indians,field,N,Kings XI Punjab,Runs,50.0,NaN,Azhar Mahmood,"['AC Gilchrist', 'Mandeep Singh', 'Azhar Mahmo...","['GJ Maxwell', 'AP Tare', 'AT Rayudu', 'RG Sha...",HDPK Dharmasena,CK Nandan
731,501242,Kochi,2011-05-05,2011,45,Kochi Tuskers Kerala,Kolkata Knight Riders,Nehru Stadium,Kolkata Knight Riders,field,N,Kochi Tuskers Kerala,Runs,17.0,NaN,BJ Hodge,"['BB McCullum', 'M Klinger', 'PA Patel', 'DPMD...","['JH Kallis', 'EJG Morgan', 'G Gambhir', 'MK T...",S Ravi,RJ Tucker
789,419151,Nagpur,2010-04-12,2009/10,46,Deccan Chargers,Royal Challengers Bangalore,"Vidarbha Cricket Association Stadium, Jamtha",Royal Challengers Bangalore,field,N,Deccan Chargers,Runs,13.0,NaN,Harmeet Singh,"['HH Gibbs', 'AC Gilchrist', 'TL Suman', 'RG S...","['MK Pandey', 'JH Kallis', 'R Dravid', 'RV Uth...",RE Koertzen,RB Tiffin
835,392239,Johannesburg,2009-05-24,2009,Final,Royal Challengers Bangalore,Deccan Chargers,New Wanderers Stadium,Royal Challengers Bangalore,field,N,Deccan Chargers,Runs,6.0,NaN,A Kumble,"['JH Kallis', 'MK Pandey', 'RE van der Merwe',...","['AC Gilchrist', 'HH Gibbs', 'TL Suman', 'A Sy...",RE Koertzen,SJA Taufel
837,392237,Centurion,2009-05-22,2009,Semi Final,Delhi Daredevils,Deccan Chargers,SuperSport Park,Deccan Chargers,field,N,Deccan Chargers,Wickets,6.0,NaN,AC Gilchrist,"['G Gambhir', 'DA Warner', 'V Sehwag', 'TM Dil...","['AC Gilchrist', 'HH Gibbs', 'AA Bilakhia', 'T...",BR Doctrove,DJ Harper
840,392234,Durban,2009-05-20,2009,54,Chennai Super Kings,Kings XI Punjab,Kingsmead,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,24.0,NaN,M Muralitharan,"['GJ Bailey', 'PA Patel', 'SK Raina', 'S Badri...","['S Sohal', 'SM Katich', 'LA Pomersbach', 'Yuv...",BG Jerling,SJA Taufel
844,392230,Bloemfontein,2009-05-17,2009,50,Delhi Daredevils,Rajasthan Royals,OUTsurance Oval,Delhi Daredevils,bat,N,Delhi Daredevils,Runs,14.0,NaN,AB de Villiers,"['G Gambhir', 'V Sehwag', 'AB de Villiers', 'T...","['RJ Quiney', 'GC Smith', 'NV Ojha', 'J Botha'...",SS Hazare,IL Howell
846,392227,Port Elizabeth,2009-05-16,2009,47,Chennai Super Kings,Mumbai Indians,St George's Park,Mumbai Indians,bat,N,Chennai Super Kings,Wickets,7.0,NaN,ML Hayden,"['PA Patel', 'ML Hayden', 'SK Raina', 'S Badri...","['ST Jayasuriya', 'DJ Bravo', 'JP Duminy', 'SR...",SK Tarapore,SJA Taufel
854,392220,Kimberley,2009-05-11,2009,40,Deccan Chargers,Rajasthan Royals,De Beers Diamond Oval,Deccan Chargers,bat,N,Deccan Chargers,Runs,53.0,NaN,DR Smith,"['TL Suman', 'AC Gilchrist', 'RG Sharma', 'A S...","['GC Smith', 'SA Asnodkar', 'LA Carseldine', '...",GAV Baxter,HDPK Dharmasena
859,392215,East London,2009-05-08,2009,35,Delhi Daredevils,Mumbai Indians,Buffalo Park,Mumbai Indians,bat,N,Delhi Daredevils,Wickets,7.0,NaN,A Nehra,"['G Gambhir', 'DA Warner', 'TM Dilshan', 'AB d...","['L Ronchi', 'JP Duminy', 'PR Shah', 'SR Tendu...",M Erasmus,SK Tarapore
880,392195,Cape Town,2009-04-26,2009,15,Kings XI Punjab,Rajasthan Royals,Newlands,Kings XI Punjab,bat,N,Kings XI Punjab,Runs,27.0,NaN,KC Sangakkara,"['RS Bopara', 'K Goel', 'KC Sangakkara', 'Yuvr...","['SA Asnodkar', 'GC Smith', 'RJ Quiney', 'YK P...",M Erasmus,K Hariharan

In [59]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

In [60]:
ipl.groupby('Season').get_group('2022')[['City', 'Season', 'MatchNumber', 'Team1', 'Team2', 'Player_of_Match', 'WinningTeam']].head()

,City,Season,MatchNumber,Team1,Team2,Player_of_Match,WinningTeam
0,Ahmedabad,2022,Final,Rajasthan Royals,Gujarat Titans,HH Pandya,Gujarat Titans
1,Ahmedabad,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,JC Buttler,Rajasthan Royals
2,Kolkata,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,RM Patidar,Royal Challengers Bangalore
3,Kolkata,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,DA Miller,Gujarat Titans
4,Mumbai,2022,70,Sunrisers Hyderabad,Punjab Kings,Harpreet Brar,Punjab Kings

In [61]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [62]:
movies.groupby('year_of_release').head(1)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India)
153,Mohalla Assi,tt4949324,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mohalla_Assi,Mohalla Assi,Mohalla Assi,0,2015,150,Comedy|Drama,6.9,1369,Based on Dr. Kashinath Singh's Hindi novel 'Ka...,A Sanskrit priest decides to take matters in n...,NaN,Sunny Deol|Sakshi Tanwar|Ravi Kishan|Saurabh S...,NaN,16 November 2018 (India)
175,Trapped (2016 Hindi film),tt6206564,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Trapped_(2016_In...,Trapped,Trapped,0,2016,105,Action|Drama|Thriller,7.5,8295,Shaurya' (Rajkummar Rao) must pluck up the cou...,A man struggles to survive after he unintentio...,NaN,Rajkummar Rao|Geetanjali Thapa|Shiladitya Sen|...,4 wins & 4 nominations,17 March 2017 (India)
186,Ek Thi Rani Aisi Bhi,tt6752836,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Ek_Thi_Rani_Aisi...,Ek Rani Aisi Bhi Thi,Ek Rani Aisi Bhi Thi,0,2013,\N,Biography|History,0.0,0,Simple but yet elegant Rajmata and her journey...,Simple but yet elegant Rajmata and her journey...,NaN,Hema Malini|Vinod Khanna|Sachin Khedekar|Rajes...,NaN,NaN
312,M Cream,tt2963974,https://upload.wikimedia.org/wikipedia/commons...,https://en.wikipedia.org/wiki/M_Cream,M Cream,M Cream,0,2014,112,Adventure|Comedy|Drama,5.7,590,FIGS is the typical cynic one finds lurking in...,A motley crew of university students set out o...,NaN,Tom Alter|Raaghav Chanana|Ira Dubey|Lushin Dub...,4 wins,22 July 2016 (India)
466,Gulabi Gang (film),tt2196638,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gulabi_Gang_(film),Gulabi Gang,Gulabi Gang,0,2012,96,Documentary,7.5,195,Bundelkhand in central India a region notorio...,In Bundelkhand India a revolution is in the ...,NaN,Sampat Pal Devi|Ram Dulari|Devrati|Babu|Soondh...,7 wins & 2 nominations,February 2014 (India)
533,Mumbhai Connection,tt1826763,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Mumbhai_Connection,Mumbhai Connection,Mumbhai Connection,0,2011,90,Comedy|Crime|Thriller,5.4,22,An Indian salesman Faisal joins an Atlanta I...,An Indian salesman Faisal joins an Atlanta I...,NaN,Alieesa P Badresia|Rafiq Batcha|Chrissy Chambe...,NaN,2013 (India)
550,Rang Rasiya,tt1239276,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Rang_Rasiya,Colours of Passion,Rang Rasiya,0,2008,132,Biography|Drama|Romance,7.1,1699,Inspired by the real life of Raja Ravi Varma ...,A look into the life of 19th century Indian pa...,A story of a great Painter| who created the pi...,Randeep Hooda|Nandana Sen|Paresh Rawal|Ashish ...,1 nomination,7 November 2014 (India)
739,Dhobi Ghat (film),tt1433810,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Dhobi_Ghat_(film),Dhobi Ghat,Dhobi Ghat,0,2010,100,Drama,7.0,11792,The lives of 4 different people in the city of...,The lives of four people intersect in Mumbai: ...,NaN,Prateik|Monica Dogra|Kriti Malhotra|Aamir Khan...,1 win & 3 nominations,21 January 2011 (India)
837,Thanks Maa,tt1437367,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Thanks_Maa,Thanks Maa,Thanks Maa,0,2009,120,Crime|Drama,8.0,666,While on the run from the reformatory a 12 ye...,A homeless petty thief attempts to find the bi...,NaN,Master Shams|Master Salman|Master Jaffer|Maste...,NaN,5 March 2010 (India)
987,Humne Jeena Seekh Liya,tt1127869,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humne_Jeena_Seek...,Humne Jeena Seekh Liya,Humne Jeena Seekh Liya,0,2007,149,Drama,7.0,43,Ashwin (Siddharth Chandekar) Lochya (Omkar Bh...,Ashwin (Siddharth Chandekar) Lochya (Omkar Bh...,NaN,Omkar Bhatkar|Siddharth Chandekar|Gaurav Chopr...,NaN,26 October 2007 (India)
1058,Black Friday (2007 film),tt0400234,https://upload.wikimedia.org/wikipedia/en/5/58...,https://en.wikipedia.org/wiki/Black_Friday_(20...,Black Friday,Black Friday,0,2004,143,Action|Crime|Drama,8.5,16761,A dramatic presentation of the bomb blasts tha...,Black Friday is a film about the investigation...,The story of the Bombay bomb blasts,Kay Kay Menon|Pavan Malhotra|Aditya Srivastava...,3 nominations,9 February 2007 (India)
1059,The Blue Umbrella (2005 film),tt0457802,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Blue_Umbrell...,The Blue Umbrella,The Blue Umbrella,0,2005,90,Comedy|Drama|Family,7.6,1663,Young Biniya lives a poor lifestyle in a small...,In a small village when a little girl's presci...,NaN,Pankaj Kapur|Shreya Sharma|Deepak Dobriyal|Rah...,2 wins,10 August 2007 (India)
1094,Kudiyon Ka Hai Zamana,tt0857385,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Kudiyon_Ka_Hai_Z...,Kudiyon Ka Hai Zamaana,Kudiyon Ka Hai Zamaana,0,2006,112,Comedy,3.6,64,Mayuri Kanika Natasha and Anjali have been ...,Mayuri Kanika Natasha and Anjali have been ...,Diamonds. Marriage. Love. Friendship. Babies.,Rekha|Mahima Chaudhry|Vasundhara Das|Kim Sharm...,NaN,2006 (India)
1254,Hazaaron Khwaishein Aisi,tt0411469,https://upload.wikimedia.org/wikipedia/commons...,https://en.wikipedia.org/wiki/Hazaaron_Khwaish...,Hazaaron Khwaishein Aisi,Hazaaron Khwaishein Aisi,0,2003,120,Drama,7.9,4413,Geeta Rao has two admirers - one is Siddharth ...,Set in the backdrop of Indian Emergency 1975 ...,A clash between idealism and realism,Kay Kay Menon|Shiney Ahuja|Chitrangda Singh|Ra...,3 wins & 6 nominations,15 April 2005 (India)
1487,Raaz (2002 film),tt0307873,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Raaz_(2002_film),Raaz,Raaz,0,2002,151,Drama|Horror|Musical,6.5,2478,Sanjana and Aditya retreat to Ooty to give a l...,Sanjana and Aditya decide to give their marria...,Do you want to know the secret,Dino Morea|Bipasha Basu|Malini Sharma|Shruti U...,4 wins & 6 nominations,12 March 2002 (Kuwait)
1512,Baaja,tt0405722,NaN,https://en.wikipedia.org/wiki/Baaja,Mouth Organ,Baaja,0,2001,\N,Family,6.6,8,NaN,Add a Plot »,NaN,Ram Awana|Saroj Bhagwar|Roni Bhatt|Chitra Pand...,NaN,NaN

In [63]:
movies.groupby('year_of_release')['imdb_votes'].mean().head()

year_of_release
2001    6356.180328
2002    2027.828947
2003    3050.989899
2004    4144.569620
2005    2408.762887
Name: imdb_votes, dtype: float64

In [64]:
movies.groupby('year_of_release')['imdb_votes'].sum().head()

year_of_release
2001    387727
2002    154115
2003    302048
2004    327421
2005    233650
Name: imdb_votes, dtype: int64

In [65]:
diabetes

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [66]:
diabetes.groupby('Outcome')['BMI'].mean().head()

Outcome
0    30.304200
1    35.142537
Name: BMI, dtype: float64

In [67]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')

In [68]:
movies.groupby('year_of_release')['title_x'].count().head()

year_of_release
2001    61
2002    76
2003    99
2004    79
2005    97
Name: title_x, dtype: int64

In [69]:
movies.groupby('year_of_release')['imdb_rating'].max().head()

year_of_release
2001    8.1
2002    8.3
2003    8.2
2004    8.7
2005    8.2
Name: imdb_rating, dtype: float64

In [70]:
movies.groupby('year_of_release')['imdb_rating'].min().head()

year_of_release
2001    3.0
2002    2.8
2003    2.1
2004    2.3
2005    2.5
Name: imdb_rating, dtype: float64

In [71]:
ipl.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='str')

In [72]:
ipl.groupby('WinningTeam')['WinningTeam'].value_counts().sort_values(ascending=False)

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Kings XI Punjab                 88
Sunrisers Hyderabad             75
Delhi Daredevils                67
Delhi Capitals                  36
Deccan Chargers                 29
Punjab Kings                    13
Gujarat Lions                   13
Gujarat Titans                  12
Pune Warriors                   12
Rising Pune Supergiant          10
Lucknow Super Giants             9
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [73]:
ipl['WinningTeam'].value_counts()

WinningTeam
Mumbai Indians                 131
Chennai Super Kings            121
Kolkata Knight Riders          114
Royal Challengers Bangalore    109
Rajasthan Royals                96
Kings XI Punjab                 88
Sunrisers Hyderabad             75
Delhi Daredevils                67
Delhi Capitals                  36
Deccan Chargers                 29
Punjab Kings                    13
Gujarat Lions                   13
Gujarat Titans                  12
Pune Warriors                   12
Rising Pune Supergiant          10
Lucknow Super Giants             9
Kochi Tuskers Kerala             6
Rising Pune Supergiants          5
Name: count, dtype: int64

In [74]:
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='str')

In [75]:
movies['runtime'].dtype

In [76]:
movies['runtime'] = pd.to_numeric(movies['runtime'], errors='coerce')

In [77]:
movies.groupby('year_of_release')['runtime'].mean().head()

year_of_release
2001    156.000000
2002    150.359375
2003    138.791209
2004    145.882353
2005    136.186813
Name: runtime, dtype: float64

In [78]:
retail = pd.read_csv("Retail_Dataset_Cleaned.csv")
retail.columns

Index(['Store_ID', 'Store_Name', 'Brand_Name', 'Store_Type', 'City',
       'City_Tier', 'Product_Name', 'Category', 'Sub_Category',
       'Product_Stage', 'Quantity_Available', 'Units_Sold', 'Unit_Price',
       'Cost_Price', 'Revenue', 'Profit_Margin', 'Average_Order_Value',
       'Inventory_Turnover', 'Days_of_Stock', 'Customer_Segment',
       'Sales_Channel', 'Payment_Method', 'Supplier', 'Supplier_Rating',
       'Promotion_Type', 'Promotion_Impact', 'Max_Discount_Offered',
       'Return_Rate', 'Return_Reason', 'Customer_Satisfaction',
       'Online_Rating', 'Review_Count', 'Sales_Rep_Experience',
       'Sales_Rep_Rating', 'Market_Share', 'Competition_Level',
       'Competitor_Count', 'Brand_Loyalty', 'Brand_Awareness',
       'Price_Competitiveness', 'Weather_Impact', 'Delivery_Time',
       'Shipping_Cost', 'Month', 'Year', 'Quarter', 'Season'],
      dtype='str')

In [79]:
retail['Revenue'] = pd.to_numeric(retail['Revenue'], errors='coerce')

In [80]:
retail.groupby(['Category', 'Sub_Category'])['Revenue'].sum()

Category         Sub_Category
Clothes          Dresses               3.076569e+07
                 Jackets               4.141522e+07
                 Jeans                 2.642349e+07
                 Shoes                 9.750387e+07
                 T-Shirts              2.595473e+07
Electronics      Headphones            2.484539e+08
                 Laptops               1.219792e+09
                 Smart Tvs             6.690648e+08
                 Smartphones           8.495754e+08
                 Tablets               6.361765e+08
Gadgets          Bluetooth Speakers    1.141583e+08
                 Cameras               1.838521e+09
                 Gaming Consoles       3.935267e+08
                 Power Banks           2.526780e+07
                 Smart Watches         2.829051e+08
Groceries        Dal                   3.892439e+06
                 Oil                   4.520413e+06
                 Rice                  6.385987e+06
                 Sugar                 1.780603e+06
                 Tea                   7.360841e+06
Home Appliances  Air Conditioners      1.549267e+08
                 Microwaves            4.765081e+07
                 Refrigerators         1.904177e+08
                 Washing Machines      1.093608e+08
                 Water Purifiers       5.605599e+07
Name: Revenue, dtype: float64

In [81]:
movies.groupby('year_of_release')['imdb_rating'].agg(['sum', 'mean', 'count']).head()

                   sum      mean  count
year_of_release
2001             343.8  5.636066     61
2002             390.8  5.142105     76
2003             546.3  5.518182     99
2004             414.9  5.251899     79
2005             519.6  5.356701     97

In [82]:
movies.groupby('year_of_release').agg({'imdb_rating': 'max', 'imdb_votes': 'sum'}).head()

                 imdb_rating  imdb_votes
year_of_release
2001                     8.1      387727
2002                     8.3      154115
2003                     8.2      302048
2004                     8.7      327421
2005                     8.2      233650

In [83]:
retail

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5141,Bx_Jaipur_077,Brandx_India Style Jaipur,Brandx_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150.0,11,2024,Q4,Winter
5142,Bx_Mumbai_067,Brandx_India Daily Mumbai,Brandx_India,Express,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136.0,7,2023,Q3,Monsoon
5143,Bx_Kanpur_097,Brandx_India Gadget Zone Kanpur,Brandx_India,Flagship,Kanpur,Tier2,Dell Xps 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222.0,7,2023,Q3,Monsoon
5144,Bx_Mumbai_031,Brandx_India Style Mumbai,Brandx_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138.0,12,2022,Q4,Winter
5145,Bx_Delhi_032,Brandx_India Electronics Delhi,Brandx_India,Flagship,Delhi,Metro,Macbook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210.0,6,2024,Q2,Monsoon

In [84]:
retail.groupby('City_Tier')['Revenue'].sum().head()

City_Tier
Metro    5.562024e+09
Tier1    5.654451e+08
Tier2    9.543883e+08
Name: Revenue, dtype: float64

In [85]:
movies.groupby('year_of_release')['imdb_rating'].agg(lambda x: (x.max() - x.min()))

year_of_release
2001    5.1
2002    5.5
2003    6.1
2004    6.4
2005    5.7
2006    6.1
2007    6.7
2008    6.3
2009    5.4
2010    5.7
2011    7.3
2012    6.1
2013    8.2
2014    8.1
2015    8.4
2016    8.4
2017    8.6
2018    6.7
2019    9.4
Name: imdb_rating, dtype: float64

In [86]:
bats

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [87]:
bats.columns

Index(['batter', 'batsman_run'], dtype='str')

In [88]:
top5 = bats.sort_values('batsman_run', ascending=False).head(5).reset_index(drop=True)
strike_rate = pd.DataFrame({
    "Strike Rate" : [128.4, 124, 125, 152, 132]
})
strike_rate

   Strike Rate
0        128.4
1        124.0
2        125.0
3        152.0
4        132.0

In [89]:
pd.concat([top5, strike_rate], axis=1).reset_index(drop=True)

      batter  batsman_run  Strike Rate
0    V Kohli         6634        128.4
1   S Dhawan         6244        124.0
2  DA Warner         5883        125.0
3  RG Sharma         5881        152.0
4   SK Raina         5536        132.0

In [90]:
pd.concat([top5, strike_rate], axis=0).reset_index(drop=True)

      batter  batsman_run  Strike Rate
0    V Kohli       6634.0          NaN
1   S Dhawan       6244.0          NaN
2  DA Warner       5883.0          NaN
3  RG Sharma       5881.0          NaN
4   SK Raina       5536.0          NaN
5        NaN          NaN        128.4
6        NaN          NaN        124.0
7        NaN          NaN        125.0
8        NaN          NaN        152.0
9        NaN          NaN        132.0