In [1]:
import pandas as pd 
import numpy as np

In [2]:
bat = pd.read_csv("batsman_runs_ipl - batsman_runs_ipl.csv")
bat

             batter  batsman_run
0    A Ashish Reddy          280
1          A Badoni          161
2        A Chandila            4
3          A Chopra           53
4       A Choudhary           25
..              ...          ...
600      Yash Dayal            0
601   Yashpal Singh           47
602     Younis Khan            3
603    Yuvraj Singh         2754
604          Z Khan          117

[605 rows x 2 columns]

In [3]:
top_batsmen = bat.sort_values("batsman_run", ascending=False).head(5).reset_index(drop=True)
print(top_batsmen)

print()

player_team = pd.DataFrame({
    'batter' : ['V Kohli', 'S Dhawan', 'DA Warner', 'RG Sharma', 'MS Dhoni'],
    'Team' : ['RCB', 'DC', 'SRH', 'MI', 'CSK']

})

print(player_team)

      batter  batsman_run
0    V Kohli         6634
1   S Dhawan         6244
2  DA Warner         5883
3  RG Sharma         5881
4   SK Raina         5536

      batter Team
0    V Kohli  RCB
1   S Dhawan   DC
2  DA Warner  SRH
3  RG Sharma   MI
4   MS Dhoni  CSK

In [4]:
pd.merge(top_batsmen, player_team, on="batter", how="inner")

      batter  batsman_run Team
0    V Kohli         6634  RCB
1   S Dhawan         6244   DC
2  DA Warner         5883  SRH
3  RG Sharma         5881   MI

In [5]:
pd.merge(top_batsmen, player_team, on="batter", how="left")

      batter  batsman_run Team
0    V Kohli         6634  RCB
1   S Dhawan         6244   DC
2  DA Warner         5883  SRH
3  RG Sharma         5881   MI
4   SK Raina         5536  NaN

In [8]:
pd.merge(top_batsmen, player_team, on="batter", how="outer")

      batter  batsman_run Team
0  DA Warner       5883.0  SRH
1   MS Dhoni          NaN  CSK
2  RG Sharma       5881.0   MI
3   S Dhawan       6244.0   DC
4   SK Raina       5536.0  NaN
5    V Kohli       6634.0  RCB

In [11]:
player_team_v2 = player_team.rename(columns={'batter':'Player Name'})

In [12]:
player_team_v2

  Player Name Team
0     V Kohli  RCB
1    S Dhawan   DC
2   DA Warner  SRH
3   RG Sharma   MI
4    MS Dhoni  CSK

In [13]:
pd.merge(top_batsmen, player_team_v2, left_on='batter', right_on='Player Name', how='inner')

      batter  batsman_run Player Name Team
0    V Kohli         6634     V Kohli  RCB
1   S Dhawan         6244    S Dhawan   DC
2  DA Warner         5883   DA Warner  SRH
3  RG Sharma         5881   RG Sharma   MI

In [15]:
season1 = pd.DataFrame({'batter':['V Kohli', 'S Dhawan'], 'runs':[973, 689]})
season2 = pd.DataFrame({'batter':['V Kohli', 'S Dhawan'], 'runs':[741, 502]})

pd.merge(season1, season2, on= 'batter', suffixes=('_2023', '_2024'))

     batter  runs_2023  runs_2024
0   V Kohli        973        741
1  S Dhawan        689        502